os: Visual Studio 2017

clone_folder: c:/projects/win-bluetooth

platform:
  - x64

configuration:
  - Debug

environment:
  matrix:
    - VS_GEN: Visual Studio 15 2017 Win64

build_script:
  - md build
  - cd build
  - cmake -Wno-dev -G"%VS_GEN%" ..
  - cmake --build . --config %CONFIGURATION%